general {
    hide_cursor = true
}

background {
    monitor =
    color = rgba(000000)
    path = screenshot
}

input-field {
    monitor =
    size = 400, 80
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(ffffff)
    inner_color = rgb(222222)
    font_color = rgb(ffffff)
    fade_on_empty = false
    placeholder_text = Password...
}
